import type { ToolDefinition } from "./types";

const phase1Tools: ToolDefinition[] = [
  {
    id: "image-compressor",
    slug: "image-compressor",
    name: "Image Compressor",
    category: "compression",
    description: "Compress supported images in the browser while balancing file size and visual quality.",
    primaryIntent: "compress an image online",
    processingMode: "browser",
    inputFormats: ["image/jpeg", "image/png", "image/webp"],
    outputFormats: ["image/jpeg", "image/png", "image/webp"],
    seo: {
      title: "Image Compressor Online | Pixora",
      description: "Compress JPG, PNG, and WebP images online with Pixora's privacy-first browser-based image compressor.",
      h1: "Compress an Image Online",
      questions: ["How do I compress an image?", "Can I reduce image file size without losing too much quality?"],
    },
    relatedTools: ["image-resizer", "jpg-to-png", "jpg-to-webp"],
    status: "phase-1",
  },
  {
    id: "image-resizer",
    slug: "image-resizer",
    name: "Image Resizer",
    category: "resize",
    description: "Resize images by dimensions or percentage with a responsive browser-based workflow.",
    primaryIntent: "resize an image online",
    processingMode: "browser",
    inputFormats: ["image/jpeg", "image/png", "image/webp"],
    outputFormats: ["image/jpeg", "image/png", "image/webp"],
    seo: {
      title: "Image Resizer Online | Pixora",
      description: "Resize JPG, PNG, and WebP images online by dimensions or percentage using Pixora.",
      h1: "Resize an Image Online",
      questions: ["How do I resize an image?", "Can I resize an image to exact pixel dimensions?"],
    },
    relatedTools: ["image-compressor", "jpg-to-png"],
    status: "phase-1",
  },
  {
    id: "jpg-to-png",
    slug: "jpg-to-png",
    name: "JPG to PNG",
    category: "conversion",
    description: "Convert JPG images to PNG format in a simple browser-based workflow.",
    primaryIntent: "convert JPG to PNG",
    processingMode: "browser",
    inputFormats: ["image/jpeg"],
    outputFormats: ["image/png"],
    seo: {
      title: "JPG to PNG Converter | Pixora",
      description: "Convert JPG to PNG online with Pixora. Fast, simple, and privacy-first browser processing.",
      h1: "Convert JPG to PNG",
      questions: ["How do I convert JPG to PNG?", "Does JPG to PNG improve image quality?"],
    },
    relatedTools: ["png-to-jpg", "jpg-to-webp", "image-compressor"],
    status: "phase-1",
  },
  {
    id: "png-to-jpg",
    slug: "png-to-jpg",
    name: "PNG to JPG",
    category: "conversion",
    description: "Convert PNG images to JPG format while keeping the workflow simple and fast.",
    primaryIntent: "convert PNG to JPG",
    processingMode: "browser",
    inputFormats: ["image/png"],
    outputFormats: ["image/jpeg"],
    seo: {
      title: "PNG to JPG Converter | Pixora",
      description: "Convert PNG to JPG online with Pixora's fast browser-based image converter.",
      h1: "Convert PNG to JPG",
      questions: ["How do I convert PNG to JPG?", "What happens to transparency when PNG is converted to JPG?"],
    },
    relatedTools: ["jpg-to-png", "webp-to-jpg", "image-compressor"],
    status: "phase-1",
  },
  {
    id: "jpg-to-webp",
    slug: "jpg-to-webp",
    name: "JPG to WebP",
    category: "conversion",
    description: "Convert JPG images to WebP for modern web delivery and smaller files.",
    primaryIntent: "convert JPG to WebP",
    processingMode: "browser",
    inputFormats: ["image/jpeg"],
    outputFormats: ["image/webp"],
    seo: {
      title: "JPG to WebP Converter | Pixora",
      description: "Convert JPG to WebP online with Pixora's browser-based image conversion tool.",
      h1: "Convert JPG to WebP",
      questions: ["Why convert JPG to WebP?", "How do I convert JPG to WebP?"],
    },
    relatedTools: ["webp-to-jpg", "image-compressor", "jpg-to-png"],
    status: "phase-1",
  },
  {
    id: "webp-to-jpg",
    slug: "webp-to-jpg",
    name: "WebP to JPG",
    category: "conversion",
    description: "Convert WebP images to widely supported JPG files directly in the browser.",
    primaryIntent: "convert WebP to JPG",
    processingMode: "browser",
    inputFormats: ["image/webp"],
    outputFormats: ["image/jpeg"],
    seo: {
      title: "WebP to JPG Converter | Pixora",
      description: "Convert WebP to JPG online with Pixora's simple privacy-first image converter.",
      h1: "Convert WebP to JPG",
      questions: ["How do I convert WebP to JPG?", "Why would I convert WebP to JPG?"],
    },
    relatedTools: ["jpg-to-webp", "png-to-jpg", "image-compressor"],
    status: "phase-1",
  },
  {
    id: "heic-to-jpg",
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    category: "conversion",
    description: "Convert supported HEIC photos to JPG for broader compatibility.",
    primaryIntent: "convert HEIC to JPG",
    processingMode: "browser",
    inputFormats: ["image/heic", "image/heif"],
    outputFormats: ["image/jpeg"],
    seo: {
      title: "HEIC to JPG Converter | Pixora",
      description: "Convert HEIC photos to JPG online with Pixora. Privacy-first processing for supported browsers.",
      h1: "Convert HEIC to JPG",
      questions: ["How do I convert HEIC to JPG?", "Why are iPhone photos saved as HEIC?"],
    },
    relatedTools: ["image-compressor", "jpg-to-webp", "jpg-to-png"],
    status: "phase-1",
  },
  {
    id: "jpg-to-pdf",
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    category: "pdf",
    description: "Convert JPG images into PDF documents with a simple browser-first workflow.",
    primaryIntent: "convert JPG to PDF",
    processingMode: "browser",
    inputFormats: ["image/jpeg"],
    outputFormats: ["application/pdf"],
    seo: {
      title: "JPG to PDF Converter | Pixora",
      description: "Convert JPG images to PDF online with Pixora's simple privacy-first converter.",
      h1: "Convert JPG to PDF",
      questions: ["How do I convert JPG to PDF?", "Can I combine multiple JPG images into one PDF?"],
    },
    relatedTools: ["pdf-to-jpg", "compress-pdf", "image-compressor"],
    status: "phase-1",
  },
  {
    id: "compress-pdf",
    slug: "compress-pdf",
    name: "Compress PDF",
    category: "pdf",
    description: "Reduce PDF file size with a clear, controlled compression workflow.",
    primaryIntent: "compress a PDF online",
    processingMode: "hybrid",
    inputFormats: ["application/pdf"],
    outputFormats: ["application/pdf"],
    seo: {
      title: "Compress PDF Online | Pixora",
      description: "Compress PDF files online with Pixora's privacy-focused PDF compression workflow.",
      h1: "Compress PDF Online",
      questions: ["How do I compress a PDF?", "How can I reduce PDF size for email?"],
    },
    relatedTools: ["jpg-to-pdf", "pdf-to-jpg"],
    status: "phase-1",
  },
  {
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    category: "pdf",
    description: "Convert PDF pages into JPG images with a browser-first workflow where supported.",
    primaryIntent: "convert PDF to JPG",
    processingMode: "hybrid",
    inputFormats: ["application/pdf"],
    outputFormats: ["image/jpeg"],
    seo: {
      title: "PDF to JPG Converter | Pixora",
      description: "Convert PDF pages to JPG images online with Pixora's privacy-first PDF converter.",
      h1: "Convert PDF to JPG",
      questions: ["How do I convert PDF to JPG?", "Can I convert a PDF page into an image?"],
    },
    relatedTools: ["jpg-to-pdf", "compress-pdf", "image-compressor"],
    status: "phase-1",
  },
];

export const toolRegistry = Object.freeze(phase1Tools);

export function getToolById(id: string): ToolDefinition | undefined {
  return toolRegistry.find((tool) => tool.id === id);
}

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return toolRegistry.find((tool) => tool.slug === slug);
}
